### ISSUE TITLE
Error while processing the refined set

### ISSUE THREAD

**Issue by VirtualChemist** [PaddlePaddle/PaddleHelix#152]
Hi,
When i executed the following command for python code under the following path (https://github.com/PaddlePaddle/PaddleHelix/tree/dev/apps/drug_target_interaction/sign)

python preprocess_pdbbind.py --data_path_refined refined-set --dataset_name pdbbind2016 --output_path out --cutoff 5

the command ended with following error.

Traceback (most recent call last):
  File "preprocess_pdbbind.py", line 362, in <module>
    process_dataset(args.data_path_core, args.data_path_refined, args.dataset_name, args.output_path, args.cutoff)
  File "preprocess_pdbbind.py", line 308, in process_dataset
    processed_dict[name] = gen_feature(path, name, featurizer)
  File "preprocess_pdbbind.py", line 80, in gen_feature
    assert x == 8
AssertionError

Looking for your support.

Thanks

**Comment by agave233** [comment]
In fact, this assert-statement is used to ensure we have removed HOH in the mol2 file, which is not necessary for the data in your case. You can just delete this line to run the code.
