### ISSUE TITLE
GEM does't work

### ISSUE THREAD

**Issue by eshinesimida** [PaddlePaddle/PaddleHelix#256]
C:\Users\dpzc7\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
C:\Users\dpzc7\anaconda3\lib\site-packages\scipy\fft\__init__.py:97: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
C:\Users\dpzc7\anaconda3\lib\site-packages\scipy\sparse\sputils.py:17: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
C:\Users\dpzc7\anaconda3\lib\site-packages\scipy\special\orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
Traceback (most recent call last):
  File "C:/Users/dpzc7/PycharmProjects/PaddleHelix-dev/apps/pretrained_compound/ChemRL/GEM/finetune_class.py", line 258, in <module>
    main(args)
  File "C:/Users/dpzc7/PycharmProjects/PaddleHelix-dev/apps/pretrained_compound/ChemRL/GEM/finetune_class.py", line 117, in main
    compound_encoder_config = load_json_config(args.compound_encoder_config)
  File "C:\Users\dpzc7\PycharmProjects\PaddleHelix-dev\pahelix\utils\basic_utils.py", line 58, in load_json_config
    return json.load(open(path, 'r'))
TypeError: expected str, bytes or os.PathLike object, not NoneType

Process finished with exit code 1

**Comment by fanxiaoyu0** [comment]
I have collate a code here for fine-tuning downstream tasks using GEM, hoping it can help you.(https://github.com/fanxiaoyu0/GEM)

**Comment by Noisyntrain** [comment]
hi eshinesimida,
     According to the error info, it seemed that the compound_encoder_config is not configed properly. Can you post the command you use to run GEM or print the compound_encoder_config path?
