### ISSUE TITLE
Encountered ImportError when using HelixFold-Single.

### ISSUE THREAD

**Issue by ZheJiangLabCode** [PaddlePaddle/PaddleHelix#262]
**When the following instructions are run：**
python helixfold_single_inference.py  --init_model=./helixfold-single.pdparams    --fasta_file=data/7O9F_B.fasta     --output_dir="./output"
**The following error message appears：**
Traceback (most recent call last):
  File "/data/home/huangjiajian/code/FrreeProtMap/paddlepaddle/helixfold-single/helixfold_single_inference.py", line 29, in <module>
    from utils.model_tape import RunTapeModel
  File "/data/home/huangjiajian/code/FrreeProtMap/paddlepaddle/helixfold-single/utils/model_tape.py", line 27, in <module>
    from tape.others.protein_sequence_model_dynamic import ProteinEncoderModel, ProteinModel
  File "/data/home/huangjiajian/code/FrreeProtMap/paddlepaddle/helixfold-single/tape/others/protein_sequence_model_dynamic.py", line 24, in <module>
    from .transformer_block import TransformerEncoder, TransformerEncoderLayer
  File "/data/home/huangjiajian/code/FrreeProtMap/paddlepaddle/helixfold-single/tape/others/transformer_block.py", line 12, in <module>
    from paddle.fluid.dygraph import Layer, LayerList
ImportError: cannot import name 'Layer' from 'paddle.fluid.dygraph' (/data/home/huangjiajian/miniconda3/envs/paddlepaddle/lib/python3.9/site-packages/paddle/fluid/dygraph/__init__.py)

**Comment by kunruiZhu** [comment]
Hi, thanks for your interest in Helixfold-Single. 
Please try to install PaddlePaddle 2.4.2 and rerun the inference command. 
The .whl file could be found at https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
