### ISSUE TITLE
运行helixfold-single-inference.py 报错

### ISSUE THREAD

**Issue by Linzy19** [PaddlePaddle/PaddleHelix#279]
(helixfold) root@0939b8ff136b:/remote-home/lzy/Helixfold/helixfold-single# python helixfold_single_inference.py 
/opt/conda/envs/esmfold/lib/python3.7/site-packages/Bio/Data/SCOPData.py:21: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  BiopythonDeprecationWarning,
Traceback (most recent call last):
  File "helixfold_single_inference.py", line 29, in <module>
    from utils.model_tape import RunTapeModel
  File "/remote-home/lzy/Helixfold/helixfold-single/utils/model_tape.py", line 27, in <module>
    from tape.others.protein_sequence_model_dynamic import ProteinEncoderModel, ProteinModel
  File "/remote-home/lzy/Helixfold/helixfold-single/tape/others/protein_sequence_model_dynamic.py", line 24, in <module>
    from .transformer_block import TransformerEncoder, TransformerEncoderLayer
  File "/remote-home/lzy/Helixfold/helixfold-single/tape/others/transformer_block.py", line 12, in <module>
    from paddle.fluid.dygraph import Layer, LayerList
ImportError: cannot import name 'Layer' from 'paddle.fluid.dygraph' (/opt/conda/envs/esmfold/lib/python3.7/site-packages/paddle/fluid/dygraph/__init__.py)
我按步骤安装后，执行过程遇到这个错误。

**Comment by haifangong** [comment]
https://github.com/EricwanAR/HelixFold-single, you may star and follow this link, as it fix all these bugs
