### ISSUE TITLE
HelixFold3中ccd_preprocessed_etkdg.pkl.gz文件读取问题

### ISSUE THREAD

**Issue by lbsskt** [PaddlePaddle/PaddleHelix#318]
Traceback (most recent call last):
  File "/work/github/helixfold3/inference.py", line 645, in <module>
    main(args)
  File "/work/github/helixfold3/inference.py", line 501, in main
    feature_dict = feature_processing_aa.process_input_json(
  File "/work/github/helixfold3/infer_scripts/feature_processing_aa.py", line 385, in process_input_json
    ccd_preprocessed_dict = load_ccd_dict(ccd_preprocessed_path)
  File "/work/github/helixfold3/infer_scripts/feature_processing_aa.py", line 30, in load_ccd_dict
    ccd_preprocessed_dict = pickle.load(fp)
  File "/anaconda3/envs/helixfold3/lib/python3.9/gzip.py", line 320, in peek
    return self._buffer.peek(n)
  File "/anaconda3/envs/helixfold3/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/anaconda3/envs/helixfold3/lib/python3.9/gzip.py", line 495, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -2 while decompressing data: inconsistent stream state

**Comment by RyanGarciaLI** [comment]
Hi, you may check `ccd_preprocessed_etkdg.pkl.gz` integrity first. You can use `md5` or `md5sum` to quickly check if this file is corrupted. Its MD5 should be `d48063ab1f1eca3788985f5b18e0ead5`
```bash
md5sum /PATH/TO/ccd_preprocessed_etkdg.pkl.gz # linux
md5 /PATH/TO/ccd_preprocessed_etkdg.pkl.gz # mac
```
If its integrity is good, the loading issue may be due to data stream format inconsistency. According to https://docs.python.org/3/library/pickle.html#data-stream-format, Python versions may use different protocols to save pickle files. The Python we use to save this pickle file is `3.7`. But both `3.9` and `3.7` can load this file in our test. You may manually set `pickle.load(fp, protocol=4)` in `/work/github/helixfold3/infer_scripts/feature_processing_aa.py", line 30, in load_ccd_dict`. 

If you still need help, let me know.

**Comment by RyanGarciaLI** [comment]
I will close this issue since there have been no further updates. If you still have a problem, re-open it.
