### ISSUE TITLE
ssDNA won't work

### ISSUE THREAD

**Issue by jkosinski** [PaddlePaddle/PaddleHelix#339]
This input:
```
{
    "entities": [
        {
            "type": "dna",
            "ccd": "TGTCTTTCC",
            "count": 1
        }
    ]
}
```
gives
```
Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/PaddleHelix/apps/protein_folding/helixfold3/inference.py", line 637, in <module>
    main(args)
  File "/g/kosinski/kosinski/software/PaddleHelix/apps/protein_folding/helixfold3/inference.py", line 442, in main
    all_entitys = preprocess_json_entity(args.input_json, args.output_dir)
  File "/g/kosinski/kosinski/software/PaddleHelix/apps/protein_folding/helixfold3/inference.py", line 87, in preprocess_json_entity
    all_entitys = preprocess.online_json_to_entity(json_path, out_dir)
  File "/g/kosinski/kosinski/software/PaddleHelix/apps/protein_folding/helixfold3/infer_scripts/preprocess.py", line 290, in online_json_to_entity
    raise RuntimeError(f'[Error] Failed to convert {len(error_ids)}/{len(entities)} entities')
RuntimeError: [Error] Failed to convert 1/1 entities
```

**Comment by leaves520** [comment]
Hi,  @jkosinski , for the polymer(include DNA, RNA, Protein) input,  we only support  `sequence` rather than `ccd`. Best practices are as follows：
```
{
    "entities": [
        {
            "type": "dna",
            "sequence": "TGTCTTTCC",
            "count": 1
        }
    ]
}
```

**Comment by jkosinski** [comment]
Ah I made a typo from copy and paste 🫢 thanks!
